In [1]:
import pandas as pd

In [ ]:
1.Dataset
2.Independent and dependent features
3.cleaning the data -> stemming ,stopwords 
4.fixx a sentence length to fix intput length
5 one hot rep,embedding layer
6.create lstm neural network
7.

In [2]:
df=pd.read_csv('news.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.shape

(20800, 5)

In [5]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
#Drop Nan Values
df=df.dropna()

In [7]:
df.shape

(18285, 5)

In [8]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [9]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [10]:
X=df.drop('label',axis=1)

In [11]:
y=df['label']

In [12]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [13]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [14]:
import tensorflow as tf

2025-03-08 07:23:41.183874: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-08 07:23:41.355381: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1741398821.427363    5236 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741398821.448949    5236 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-08 07:23:41.613370: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [15]:
tf.__version__

'2.18.0'

In [16]:
from tensorflow.keras.layers import Embedding # helps like word 2 vec
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [30]:
#one hot 
messages=X.copy()

In [31]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [32]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [33]:
import nltk
import re #regular exp
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/rgukt-
[nltk_data]     basar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [34]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages.iloc[i]['title'])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [35]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [36]:
voc_size=5000

In [38]:
onehot_rep=[one_hot(words,voc_size) for words in corpus]
onehot_rep

[[4962, 4235, 2561, 1286, 3387, 1872, 2522, 3076, 1836, 3328],
 [159, 3541, 3643, 4059, 1624, 4977, 129],
 [1835, 3334, 1250, 2705],
 [4086, 87, 2840, 2548, 3368, 42],
 [3726, 1624, 238, 3112, 3266, 2640, 1624, 4907, 2326, 1730],
 [1372,
  1699,
  4935,
  1541,
  4546,
  316,
  4913,
  1601,
  1433,
  3535,
  52,
  672,
  1815,
  2765,
  129],
 [3537, 2028, 2650, 681, 1021, 3185, 278, 3472, 4124, 1619, 1448],
 [4513, 1368, 2619, 2334, 4972, 2217, 316, 82, 4124, 1619, 1448],
 [2710, 3371, 2840, 4974, 3525, 1815, 1512, 2075, 316, 1152],
 [586, 2200, 4480, 1597, 1878, 1624, 4363, 3252],
 [2609, 1338, 1921, 1228, 2036, 1354, 968, 3011, 4771, 3036, 3687],
 [2548, 3081, 3387, 1815, 316, 4972],
 [1092, 4582, 4014, 3651, 2597, 3917, 3671, 4338, 2239],
 [4989, 1012, 1567, 3352, 4618, 1598, 2141, 4124, 1619, 1448],
 [849, 2990, 1265, 3544, 1635, 4124, 1619, 1448],
 [4614, 4068, 1178, 1195, 2538, 3482, 353, 3119, 3289, 3224],
 [1253, 866, 3541],
 [2177, 4854, 2945, 710, 316, 1648, 4117, 129],
 [4

In [39]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [42]:
onehot_rep[1] #index of those words

[159, 3541, 3643, 4059, 1624, 4977, 129]

## Embedding Representation

In [50]:
sent_length=20
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)

In [51]:
print(embedded_docs)

[[   0    0    0 ... 3076 1836 3328]
 [   0    0    0 ... 1624 4977  129]
 [   0    0    0 ... 3334 1250 2705]
 ...
 [   0    0    0 ... 4124 1619 1448]
 [   0    0    0 ...  466 4147 4433]
 [   0    0    0 ... 3761 3758 2293]]


In [53]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,  159, 3541, 3643, 4059, 1624, 4977,  129], dtype=int32)

## creating model

In [54]:
embedding_vector_features=40 #every feature representtion into 40 dimens
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


/home/rgukt-basar/myenv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-03-08 07:47:56.946795: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [55]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [61]:
embedded_docs.shape,y.shape

((18285, 20), (18285,))

In [59]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [60]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,test_size=0.3,random_state=42)

In [72]:
## finally training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)


Epoch 1/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.9974 - loss: 0.0074 - val_accuracy: 0.9118 - val_loss: 0.5461
Epoch 2/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9988 - loss: 0.0066 - val_accuracy: 0.9087 - val_loss: 0.6344
Epoch 3/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - accuracy: 0.9992 - loss: 0.0034 - val_accuracy: 0.9087 - val_loss: 0.6527
Epoch 4/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - accuracy: 0.9991 - loss: 0.0036 - val_accuracy: 0.9052 - val_loss: 0.6908
Epoch 5/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9992 - loss: 0.0034 - val_accuracy: 0.9110 - val_loss: 0.6743
Epoch 6/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.9997 - loss: 0.0025 - val_accuracy: 0.9110 - val_loss: 0.6461
Epoch 7/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.9997 - loss: 0.0015 - val_accuracy: 0.9096 - val_loss: 0.7337
Epoch 8/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.9996 - loss: 0.0015 - val_accu

## performance metrices  and Accuracy

In [74]:
y_pred=model.predict(X_test)

172/172 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step   


In [75]:
y_pred=np.where(y_pred>0.5,1,0)

In [80]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


array([[2848,  259],
       [ 234, 2145]])

In [81]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9101348888078746

In [82]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3107
           1       0.89      0.90      0.90      2379

    accuracy                           0.91      5486
   macro avg       0.91      0.91      0.91      5486
weighted avg       0.91      0.91      0.91      5486



## prediction of model

In [106]:
import pickle
with open('tokenizer.pkl', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [108]:
model.save('fake_news_model.h5')

In [109]:
import pickle
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import load_model

# Load Tokenizer
with open('tokenizer.pkl', 'rb') as handle:
    tokenizer = pickle.load(handle)

# Load Trained Model
model = load_model('fake_news_model.h5')  # Ensure the model is saved as 'fake_news_model.h5'

# Define max length (must be same as during training)
MAX_LENGTH = 100  # Change if different in training

def preprocess_text(text):
    """Function to preprocess input text similar to training data."""
    import re
    from nltk.corpus import stopwords
    from nltk.stem.porter import PorterStemmer

    ps = PorterStemmer()
    text = re.sub('[^a-zA-Z]', ' ', text)  # Remove special characters
    text = text.lower().split()
    text = [ps.stem(word) for word in text if word not in stopwords.words('english')]
    return ' '.join(text)

def predict_news(review):
    """Function to predict whether news is fake or real."""
    processed_review = preprocess_text(review)  # Preprocess the text
    sequence = tokenizer.texts_to_sequences([processed_review])  # Convert to sequence
    padded_sequence = pad_sequences(sequence, maxlen=MAX_LENGTH, padding='post')  # Pad sequence
    
    prediction = model.predict(padded_sequence)[0][0]  # Get model prediction
    return "Fake News" if prediction > 0.5 else "Real News"



In [117]:
# Example Usage
news_title = input("Enter a news headline: ")
result = predict_news(news_title)
print(f"Prediction: {result}")


Enter a news headline:   'flynn hillari clinton big woman campu breitbart'


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Prediction: Fake News
