In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('spam.csv')

In [3]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
# creating new column
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [14]:
df.shape

(5572, 3)

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [15]:
X_train.shape

(4457,)

In [16]:
X_test.shape

(1115,)

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
type(X_train)

pandas.core.series.Series

In [23]:
X_train[:2]

5184    I'm in town now so i'll jus take mrt down later.
1255                          What your plan for pongal?
Name: Message, dtype: object

In [24]:
y_train

5184    0
1255    0
4659    0
2526    0
2959    1
       ..
2866    0
1491    0
2202    0
73      0
4126    0
Name: spam, Length: 4457, dtype: int64

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()

X_train_cv=v.fit_transform(X_train)



In [33]:
X_train_cv.toarray() # vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [38]:
#to know methods
import numpy as np
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [39]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [40]:
v.vocabulary_

{'in': 3629,
 'town': 6970,
 'now': 4828,
 'so': 6251,
 'll': 4143,
 'jus': 3860,
 'take': 6660,
 'mrt': 4592,
 'down': 2426,
 'later': 4012,
 'what': 7449,
 'your': 7682,
 'plan': 5221,
 'for': 2928,
 'pongal': 5289,
 'this': 6820,
 'message': 4435,
 'is': 3732,
 'from': 3010,
 'great': 3227,
 'doctor': 2376,
 'india': 3648,
 'do': 2371,
 'not': 4813,
 'drink': 2448,
 'appy': 1037,
 'fizz': 2870,
 'it': 3744,
 'contains': 1981,
 'cancer': 1640,
 'causing': 1695,
 'age': 864,
 'say': 5904,
 'slowly': 6209,
 'god': 3156,
 'love': 4208,
 'you': 7677,
 'amp': 949,
 'need': 4706,
 'clean': 1835,
 'my': 4642,
 'heart': 3373,
 'with': 7522,
 'blood': 1403,
 'send': 5985,
 'to': 6902,
 'ten': 6733,
 'special': 6331,
 'people': 5132,
 'miracle': 4482,
 'tomorrow': 6927,
 'pls': 5246,
 'have': 3347,
 'secret': 5950,
 'admirer': 824,
 'reveal': 5751,
 'who': 7469,
 'thinks': 6815,
 'call': 1609,
 '09065174042': 220,
 'opt': 4953,
 'out': 4996,
 'reply': 5702,
 'stop': 6465,
 '50': 542,
 'per': 5

In [53]:
print(X_train[1])
print("\n",X_train[1][0])

Ok lar... Joking wif u oni...

 O


In [96]:
#Building  model

In [59]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [60]:
X_test_cv=v.transform(X_test)

In [63]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.94      0.95      0.94       152

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [86]:
#now check
emails=[
    'hi kalyan how r u?',
    'hey kalyan 20% free,and 10% discount',
    'Do visit out store'
]

In [87]:
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1, 0])

In [89]:
#observe the above message are classified into spam and not spam 
#based on the initially provided data
#so 

In [90]:
# Easy way another using pipline
from sklearn.pipeline import Pipeline

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])


In [93]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [104]:
y_pred=clf.predict(X_test)
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      0.99      0.99       963\n           1       0.94      0.95      0.94       152\n\n    accuracy                           0.98      1115\n   macro avg       0.97      0.97      0.97      1115\nweighted avg       0.98      0.98      0.98      1115\n'

In [105]:
#now check
emails=[
    'hi kalyan how r u?',
    'hey kalyan 20% free,and 10% discount',
    'Do visit out store'
]

In [107]:
predictions = clf.predict(emails)

In [108]:
predictions

array([0, 1, 0])

In [109]:
# Print results
for email, pred in zip(emails, predictions):
    label = "Spam" if pred == 1 else "Not Spam"
    print(f"Email: '{email}' → Prediction: {label}")


Email: 'hi kalyan how r u?' → Prediction: Not Spam
Email: 'hey kalyan 20% free,and 10% discount' → Prediction: Spam
Email: 'Do visit out store' → Prediction: Not Spam
